# Welcome to my xinit!
picom & 
xsetroot -cursor_name left_ptr &
#xrdb .Xresources
xmodmap .xmodmap
xcape -e 'Control_L=Escape'
#wmname compiz

# Enable screen locking
#xss-lock -- slock &

# Execute environment
pape maso &
polybar -r mybar &
exec herbstluftwm
